
GET  http://127.0.0.1:4000/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImtldmluIiwiZW1haWwiOiJrZXZpbkB0ZXN0LmNvbSIsImlhdCI6MTYxNjU3ODQ0Nn0.ypLTf-1mQyUPJ-YVKsLXaMmPUGh5juopnNd529pwCfs